# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

base_image: &base_image
  image: circleci/node:10


build_image: &build_image
  docker:
    - <<: *base_image
  working_directory: ~/repo

save: &save
  save_cache:
    key: node_modules-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

restore: &restore
  restore_cache:
    keys: 
      - node_modules-{{ checksum "package-lock.json" }}
      - node_modules-

jobs:
  build:
    <<: *build_image
    steps:
      - checkout

  upload_lock:
    <<: *build_image
    steps:
      - <<: *restore
      - run: sudo npm install greenkeeper-lockfile@2 -g
      - run: greenkeeper-lockfile-upload
      - <<: *save

  install:
    <<: *build_image
    steps:
      - <<: *restore
      - run: case $CIRCLE_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
      - <<: *save

  lint:
    <<: *build_image
    steps:
      - run: npm run lint
  flow:
    <<: *build_image
    steps:
      - run: npm run flow
  audit:
    <<: *build_image
    steps:
      - run: npm audit
  test:
    <<: *build_image
    steps:
      - run: npm run test:coverage
  analytics:
    <<: *build_image
    steps:
      - run: npm run analytics
  build-asset:
    <<: *build_image
    steps:
      - run: npm run build
  build-storybook:
    <<: *build_image
    steps:
      - run: npm run build-storybook

workflows:
  version: 2
  exec:
    jobs:
      - build
      - install:
          requires:
            - build
      - upload_lock:
          requires:
            - install
      - lint:
          requires:
            - install
      - flow:
          requires:
            - install
      - audit:
          requires:
            - install
      - test:
          requires:
            - install
      - analytics:
          requires:
            - install
      - build-asset:
          requires:
            - install
      - build-storybook:
          requires:
            - install
