# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

base_image: &base_image
  image: circleci/node:10


build_image: &build_image
  docker:
    - <<: anybase_image
  working_directory: ~/repo

save_lock: &save_lock
  save_cache:
    key: node_modules-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

restore_lock: &restore_lock
  restore_cache:
    keys: 
      - node_modules-{{ checksum "package-lock.json" }}

save: &save
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .
      - ".git"
      - "~/.ssh"
      - "~/repo"

restore: &restore
  restore_cache:
    keys: 
      - code-{{ .Revision }}

jobs:
  upload_lock:
    <<: anybuild_image
    # workaround for greenkeeper-lockfile-upload
    environment:
      GIT_AUTHOR_NAME: greenkeeperio-bot
      GIT_AUTHOR_EMAIL: support@greenkeeper.io
      GIT_COMMITTER_NAME: greenkeeperio-bot
      GIT_COMMITTER_EMAIL: support@greenkeeper.io
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npx --package greenkeeper-lockfile@2 greenkeeper-lockfile-upload

  install:
    <<: anybuild_image
    # workaround for greenkeeper-lockfile-update
    environment:
      GIT_AUTHOR_NAME: greenkeeperio-bot
      GIT_AUTHOR_EMAIL: support@greenkeeper.io
      GIT_COMMITTER_NAME: greenkeeperio-bot
      GIT_COMMITTER_EMAIL: support@greenkeeper.io
    steps:
      - checkout
      - <<: anyrestore_lock
      - run: case $CIRCLE_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
      - run: npx --package greenkeeper-lockfile@2 greenkeeper-lockfile-update
      - <<: anysave_lock
      - <<: anysave

  lint:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npm run lint
  typecheck:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npm run typecheck
  audit:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npm audit
  test:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run:
          name: start agreed server
          command: npm run test:agreed
          background: true
      - run: npm run test:coverage
  analytics:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npm run analytics
  build-asset:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npm run build
  build-storybook:
    <<: anybuild_image
    steps:
      - <<: anyrestore
      - <<: anyrestore_lock
      - run: npm run build-storybook

workflows:
  version: 2
  exec:
    jobs:
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - audit:
          requires:
            - install
      - test:
          requires:
            - install
      - analytics:
          requires:
            - install
      - build-asset:
          requires:
            - install
      - build-storybook:
          requires:
            - install
      - upload_lock:
          requires:
            - lint
            - typecheck
            - audit
            - build-asset
            - build-storybook
            - test
